spring:
  application:
    name=springboot-security6
  datasource:
    url: jdbc:mysql://learnspringsecurity.cx4swi2q40pf.us-east-1.rds.amazonaws.com/EazyBytes
    username: admin
    password: learnSpringSecurity
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update


#spring.security.user.name=Eazybytes
#spring.security.user.password=12345


